name: Docs

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - uses: mpewsey/doxygen-action@v1.9.2
        with:
          working-directory: 'Docs~/'
          doxyfile-path: 'Doxyfile'

      - name: Deploy
        uses: mpewsey/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Docs~/output/html
